name: Build

on: [ push, workflow_dispatch ]

jobs:
  examples:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        tf-version: [ 1.3.2 ]
    steps:
      - name: Install terraform v${{ matrix.tf-version }}
        run: |
          curl -LO https://releases.hashicorp.com/terraform/${{ matrix.tf-version }}/terraform_${{ matrix.tf-version }}_linux_amd64.zip
          unzip terraform_${{ matrix.tf-version }}_linux_amd64.zip
          sudo mv terraform /usr/local/bin
          rm *
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@1feaef8f3b6f6f22261b7e7c827ff1ae9cdd3c2b # v0.2.5
        with:
          image-tag: 'latest'
          install-awslocal: 'true'
      - name: Validate examples terraform v${{ matrix.tf-version }}
        run: make examples
  build:
    needs: [examples]
    runs-on: ubuntu-latest
    steps:
      - run: echo "OK"
